name: pos_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.2.14  # Add the flutter_native_splash package
  flutter_localization: ^0.3.0
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  pdf: ^3.11.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  theme_provider: ^0.6.0
  firebase_analytics: ^11.3.6
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png  # Add your splash logo here
    - assets/notification.png
    - assets/Laptop.jpg
flutter_native_splash:
  color: "#ffffff"  # Background color for splash screen
  image: assets/splash_screen_logo.png  # Path to the logo image
  android: true  # Enable splash screen on Android
  ios: true      # Enable splash screen on iOS
